import { jsPDF } from "jspdf";

const PRED_COLORS = { Pass: [52, 211, 153], Fail: [251, 146, 60], "At-Risk": [248, 113, 113] };
const PRED_EMOJI = { Pass: "\uD83C\uDF93", Fail: "\uD83D\uDCC9", "At-Risk": "\u26A0\uFE0F" };

function section(doc, y, title) {
  doc.setFontSize(11);
  doc.setTextColor(100, 100, 100);
  doc.text(title.toUpperCase(), 20, y);
  doc.setDrawColor(200, 200, 200);
  doc.line(20, y + 2, 190, y + 2);
  return y + 8;
}

function bullet(doc, y, text, indent = 22) {
  doc.setFontSize(10);
  doc.setTextColor(60, 60, 60);
  doc.text("\u2022  " + text, indent, y, { maxWidth: 166 });
  const lines = doc.splitTextToSize("\u2022  " + text, 166);
  return y + lines.length * 5 + 2;
}

export function generateReport(result, analysis = {}) {
  const doc = new jsPDF("p", "mm", "a4");
  const pred = result.prediction;
  const rgb = PRED_COLORS[pred] || [100, 100, 100];
  let y = 20;

  // Header bar
  doc.setFillColor(...rgb);
  doc.rect(0, 0, 210, 42, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("AcademicAI", 20, 18);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text("Student Performance Prediction Report", 20, 26);

  doc.setFontSize(9);
  doc.text(new Date().toLocaleDateString("en-IN", { year: "numeric", month: "long", day: "numeric" }), 20, 34);

  y = 54;

  // Prediction result
  doc.setFontSize(28);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...rgb);
  doc.text(`${PRED_EMOJI[pred] || ""}  ${pred}`, 20, y);
  y += 10;

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80, 80, 80);
  doc.text(`Confidence: ${result.confidence}%`, 20, y);
  y += 8;

  // Scores table
  const scores = Object.entries(result.confidence_scores || {});
  if (scores.length) {
    y = section(doc, y + 4, "Confidence Breakdown");
    scores.forEach(([label, pct]) => {
      doc.setFontSize(10);
      doc.setTextColor(60, 60, 60);
      doc.text(label, 22, y);
      doc.text(`${pct}%`, 160, y);
      // bar
      doc.setFillColor(220, 220, 220);
      doc.roundedRect(70, y - 3.5, 80, 3, 1, 1, "F");
      const rgb2 = PRED_COLORS[label] || [150, 150, 150];
      doc.setFillColor(...rgb2);
      doc.roundedRect(70, y - 3.5, Math.max(1, 80 * (pct / 100)), 3, 1, 1, "F");
      y += 8;
    });
  }

  // Risks
  const { risks = [], strengths = [], actions = [] } = analysis;
  if (risks.length) {
    y = section(doc, y + 4, "Risk Factors");
    risks.forEach(r => {
      y = bullet(doc, y, `${r.factor} — ${r.msg}`);
    });
  }

  if (strengths.length) {
    y = section(doc, y + 4, "Strengths");
    strengths.forEach(s => {
      y = bullet(doc, y, `${s.factor} — ${s.msg}`);
    });
  }

  if (actions.length) {
    y = section(doc, y + 4, "Action Plan");
    actions.forEach((a, i) => {
      doc.setFontSize(10);
      doc.setTextColor(60, 60, 60);
      doc.setFont("helvetica", "bold");
      doc.text(`${i + 1}.`, 22, y);
      doc.setFont("helvetica", "normal");
      const lines = doc.splitTextToSize(a.text, 158);
      doc.text(lines, 28, y);
      y += lines.length * 5 + 3;
    });
  }

  // Tip
  if (result.tip) {
    y = section(doc, y + 4, "What This Means");
    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);
    const tipLines = doc.splitTextToSize(result.tip, 166);
    doc.text(tipLines, 22, y);
    y += tipLines.length * 5 + 4;
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(160, 160, 160);
  doc.text(
    `Model: ${result.model_used || "Random Forest"} | Accuracy: ${result.model_accuracy || "81.0%"} | Dataset: ${result.dataset_size || 395} students`,
    20, 285
  );
  doc.text("Generated by AcademicAI — academicai.vercel.app", 20, 290);

  doc.save("AcademicAI-Report.pdf");
}